### ISSUE TITLE
removal of doit-graphx from pydoit org

### ISSUE THREAD

**Issue by schettino72** [pydoit/doit-graphx#5]
@ankostis 

Seems this project is broken, it was never released and you are not interested in maintaining it anymore [1].

I also do not want to maintain it, i think it will be better to remove it from pydoit organisation.
Could you please move the project out? Or i will just delete it...

[1] https://github.com/pydoit/doit-graphx/issues/4#issuecomment-297285287

**Comment by ankostis** [comment]
Yes, that's the situation.
You may delete it.

**Comment by schettino72** [comment]
ok. I forked it here: schettino72/doit-graphx for historical interest.

**Comment by schettino72** [comment]
Actually github has "transfer" option. nice it added a redirect and transferred. issues...
